tiantian/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^user/', include('tt_user.urls', namespace='user')),
    url(r'^order/', include('tt_order.urls', namespace='order')),
    url(r'^cart/', include('tt_cart.urls', namespace='cart')),
    url(r'^', include('tt_goods.urls', namespace='goods')),
]

tt_cart/urls.py
from django.conf.urls import url

urlpatterns = [

]

tt_user/urls.py
from django.conf.urls import url
from tt_user import views
urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^register_handle/$', views.register_handle, name='register_handle'),
    url(r'^check_user_exist/$', views.check_user_exist, name='check_user_exist'),
    url(r'^active/(.*)/$', views.register_active, name='active'),

    url(r'^login/$', views.login, name='login'),
    url(r'^login_check/$', views.login_check, name='login_check'),
    url(r'^logout/$', views.logout, name='logout'),
    # url(r'^send/$', views.send, name='send'),
    url(r'^$', views.user, name='user'),
    url(r'^order/$', views.order, name='order'),
    url(r'^address/$', views.address, name='address'),
    url(r'^address_handle/$', views.address_handle, name='address_handle'),


]

templates/base.html
{# 首页 登录 注册的父模板 #}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load staticfiles %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>{% block title %}{% endblock title %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
	{% block topfiles %}{% endblock topfiles %}
</head>
<body>
{% block header_con %}
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
                {% if request.session.islogin %}
				<div class="login_btn fl">
					欢迎您：<em>{{ request.session.username }}</em>
                    <span>|</span>
					<a href='{%  url 'user:logout' %}'>退出</a>
				</div>
                {% else %}
				<div class="login_btn fl">
					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>
                {% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="../../static/user_center_info.html">用户中心</a>
					<span>|</span>
					<a href="../../static/cart.html">我的购物车</a>
					<span>|</span>
					<a href="../../static/user_center_order.html">我的订单</a>
				</div>
			</div>
		</div>		
	</div>
{% endblock header_con %}
{#网页搜索框#}
{% block search_bar %}
	<div class="search_bar clearfix">
		<a href="base.html" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
		<div class="guest_cart fr">
			<a href="#" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">1</div>
		</div>
	</div>
{% endblock search_bar %}
{# 网页内容块 #}
{% block body %} {% endblock body %}

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
{#    底部元素#}
    {% block bottom %}{% endblock bottom %}
    {% block bottomfiles %}{% endblock bottomfiles %}
</body>
</html>

templates/detail_list_base.html
{# 详情 列表父模板 #}
{% extends 'base.html' %}
{% block body %}
    <div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
					<li><a href="#" class="fruit">新鲜水果</a></li>
					<li><a href="#" class="seafood">海鲜水产</a></li>
					<li><a href="#" class="meet">猪牛羊肉</a></li>
					<li><a href="#" class="egg">禽类蛋品</a></li>
					<li><a href="#" class="vegetables">新鲜蔬菜</a></li>
					<li><a href="#" class="ice">速冻食品</a></li>
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>
    {% block main_content %}{% endblock main_content %}
{% endblock body %}

templates/not_cart_base.html
{# 购物车,提交订单父模板 #}
{% extends 'base.html' %}
{% load staticfiles %}
{% block search_bar %}
    <div class="search_bar clearfix">
		<a href="../templates/tt_goods/index.html" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;{% block page_title %}{% endblock page_title %}</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
	</div>
{% endblock search_bar%}

templates/user_centet_base.html
{#用户中心三个模板#}
{% extends 'not_cart_base.html' %}
{% block title %}天天生鲜-用户中心{% endblock title %}
{% block page_title %}用户中心{% endblock page_title %}
{% block body %}

    <div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:user' %}" {% if page == 'user' %} class="active"{% endif %}>· 个人信息</a></li>
				<li><a href="{% url 'user:order' %}" {% if page == 'order' %} class="active"{% endif %}>· 全部订单</a></li>
				<li><a href="{% url 'user:address' %}" {% if page == 'address' %} class="active"{% endif %}>· 收货地址</a></li>
			</ul>
		</div>
        {% block right_content %}{% endblock right_content %}
    </div>
{% endblock body %}